<?php
/**
 * Created by PhpStorm.
 * User: toretto
 * Date: 15/12/14
 * Time: 22:26
 */

namespace Trt\Doctrine\Cache\Tests\Encryptor;


final class Text
{

    public static $longText = <<<PHP
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed isti ipsi, qui voluptate et dolore omnia metiuntur, nonne clamant sapienti plus semper adesse quod velit quam quod nolit? Ergo in eadem voluptate eum, qui alteri misceat mulsum ipse non sitiens, et eum, qui illud sitiens bibat? Est autem officium, quod ita factum est, ut eius facti probabilis ratio reddi possit. Non minor, inquit, voluptas percipitur ex vilissimis rebus quam ex pretiosissimis. Quam haec sunt contraria! hic si definire, si dividere didicisset, si loquendi vim, si denique consuetudinem verborum teneret, numquam in tantas salebras incidisset. Duo Reges: constructio interrete. De bona autem fama-quam enim appellant eÈdoj¤an, aptius est bonam famam hoc loco appellare quam gloriam-Chrysippus quidem et Diogenes detracta utilitate ne digitum quidem eius causa porrigendum esse dicebant; Quodsi, ne quo incommodo afficiare, non relinques amicum, tamen, ne sine fructu alligatus sis, ut moriatur optabis. </p>

<p>Quam ob rem utique idem faciunt, ut si laevam partem neglegerent, dexteram tuerentur, aut ipsius animi, ut fecit Erillus, cognitionem amplexarentur, actionem relinquerent. Illi autem, quibus summum bonum sine virtute est, non dabunt fortasse vitam beatam habere, in quo iure possit gloriari, etsi illi quidem etiam voluptates faciunt interdum gloriosas. Nam Metrodorum non puto ipsum professum, sed, cum appellaretur ab Epicuro, repudiare tantum beneficium noluisse; Eamne rationem igitur sequere, qua tecum ipse et cum tuis utare, profiteri et in medium proferre non audeas? Sed hoc summum bonum, quod tertia significatione intellegitur, eaque vita, quae ex summo bono degitur, quia coniuncta ei virtus est. Ex quo intellegitur idem illud, solum bonum esse, quod honestum sit, idque esse beate vivere: honeste, id est cum virtute, vivere. Atque his tribus generibus honestorum notatis quartum sequitur et in eadem pulchritudine et aptum ex illis tribus, in quo inest ordo et moderatio. Quem enim deditum voluptatibus, quem cupiditatum incendiis inflammatum in iis potiendis, quae acerrime concupivisset, tanta laetitia perfundi arbitramur, quanta aut superiorem Africanum Hannibale victo aut posteriorem Karthagine eversa? Ita, quem ad modum in senatu semper est aliquis, qui interpretem postulet, sic, isti nobis cum interprete audiendi sunt. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Quin etiam ferae, inquit Pacuvius, quíbus abest, ad praécavendum intéllegendi astútia, iniecto terrore mortis horrescunt. Quasi enim emendum eis sit, quod addant ad virtutem, primum vilissimas res addunt, dein singulas potius, quam omnia, quae prima natura approbavisset, ea cum honestate coniungerent. Haec non erant eius, qui innumerabilis mundos infinitasque regiones, quarum nulla esset ora, nulla extremitas, mente peragravisset. Quis contra in illa aetate pudorem, constantiam, etiamsi sua nihil intersit, non tamen diligat? </p>

<p>Hoc foedus facere si potuerunt, faciant etiam illud, ut aequitatem, modestiam, virtutes omnes per se ipsas gratis diligant. Bonum appello quicquid secundurn naturam est, quod contra malum, nec ego solus, sed tu etiam, Chrysippe, in foro, domi; Deque his rebus satis multa in nostris de re publica libris sunt dicta a Laelio. Quae cum praeponunt, ut sit aliqua rerum selectio, naturam videntur sequi; Tolletur enim appetitus animi, si, ut in lis rebus, inter quas nihil interest, neutram in partem propensiores sumus, item in nobismet ipsis quem ad modum affecti simus nihil nostra arbitrabimur interesse. At quanta conantur! Mundum hunc omnem oppidum esse nostrum! Incendi igitur eos, qui audiunt, vides. Nam diligi et carum esse iucundum est propterea, quia tutiorem vitam et voluptatem pleniorem efficit. Suis cuiusque sensibus sic, ut, contra si quis dicere velit, non audiatur -, tamen, ne quid praetermittamus, rationes quoque, cur hoc ita sit, afferendas puto. Necesseque est, si quis sibi ipsi inimicus est, eum quae bona sunt mala putare, bona contra quae mala, et quae appetenda fugere, quae fugienda appetere, quae sine dubio vitae est eversio. </p>

<p>Respondebo me non quaerere, inquam, hoc tempore quid virtus efficere possit, sed quid constanter dicatur, quid ipsum a se dissentiat. Ex quo magnitudo quoque animi existebat, qua facile posset repugnari obsistique fortunae, quod maximae res essent in potestate sapientis. Sic, quod est extremum omnium appetendorum atque ductum a prima commendatione naturae, multis gradibus adscendit, ut ad summum perveniret, quod cumulatur ex integritate corporis et ex mentis ratione perfecta. Quod quoniam in quo sit magna dissensio est, Carneadea nobis adhibenda divisio est, qua noster Antiochus libenter uti solet. In homine autem summa omnis animi est et in animo rationis, ex qua virtus est, quae rationis absolutio definitur, quam etiam atque etiam explicandam putant. Sed cum, quod honestum sit, id solum bonum esse dicamus, consentaneum tamen est fungi officio, cum id officium nec in bonis ponamus nec in malis. Quid, si reviviscant Platonis illi et deinceps qui eorum auditores fuerunt, et tecum ita loquantur? At vero Callipho et post eum Diodorus, cum is alter voluptatem adamavisset, alter vacuitatem doloris, neuter honestate carere potuit, quae est a nostris laudata maxime. At ille pellit, qui permulcet sensum voluptate. </p>

<p>Ita ceterorum sententiis semotis relinquitur non mihi cum Torquato, sed virtuti cum voluptate certatio. Quae iam oratio non a philosopho aliquo, sed a censore opprimenda est. Satis est tibi in te, satis in legibus, satis in mediocribus amicitiis praesidii. </p>

<p>Quam ob rem turpe putandum est, non dico dolere-nam id quidem est interdum necesse-, sed saxum illud Lemnium clamore Philocteteo funestare, Quod eiulatu, questu, gemitu, fremitibus Resonando mutum flebiles voces refert. Nihil enim arbitror esse magna laude dignum, quod te praetermissurum credam aut mortis aut doloris metu. Quid tibi, Torquate, quid huic Triario litterae, quid historiae cognitioque rerum, quid poetarum evolutio, quid tanta tot versuum memoria voluptatis affert? Tamen aberramus a proposito, et, ne longius, prorsus, inquam, Piso, si ista mala sunt, placet. Quocumque enim modo summum bonum sic exponitur, ut id vacet honestate, nec officia nec virtutes in ea ratione nec amicitiae constare possunt. Nec mihi illud dixeris: Haec enim ipsa mihi sunt voluptati, et erant illa Torquatis. Atqui si, ut convenire debet inter nos, est quaedam appetitio naturalis ea, quae secundum naturam sunt, appetens, eorum omnium est aliquae summa facienda. Nam cum Academicis incerta luctatio est, qui nihil affirmant et quasi desperata cognitione certi id sequi volunt, quodcumque veri simile videatur. Nunc omni virtuti vitium contrario nomine opponitur. Ac tamen, ne cui loco non videatur esse responsum, pauca etiam nunc dicam ad reliquam orationem tuam. Quae quidem adhuc peregrinari Romae videbatur nec offerre sese nostris sermonibus, et ista maxime propter limatam quandam et rerum et verborum tenuitatem. Iam argumenti ratione conclusi caput esse faciunt ea, quae perspicua dicunt, deinde ordinem sequuntur, tum, quid verum sit in singulis, extrema conclusio est. Non enim, si malum est dolor, carere eo malo satis est ad bene vivendum. Ratio ista, quam defendis, praecepta, quae didicisti, quae probas, funditus evertunt amicitiam, quamvis eam Epicurus, ut facit, in caelum efferat laudibus. Quod enim vituperabile est per se ipsum, id eo ipso vitium nominatum puto, vel etiam a vitio dictum vituperari. Quo minus animus a se ipse dissidens secumque discordans gustare partem ullam liquidae voluptatis et liberae potest. Itaque non discedit ab eorum curatione, quibus praeposita vitam omnem debet gubernare, ut mirari satis istorum inconstantiam non possim. Illa enim, quae sunt a nobis bona corporis numerata, complent ea quidem beatissimam vitam, sed ita, ut sine illis possit beata vita existere. </p>

<p>Verum enim diceret, idque Socratem, qui voluptatem nullo loco numerat, audio dicentem, cibi condimentum esse famem, potionis sitim. Quoniam, inquiunt, omne peccatum inbecillitatis et inconstantiae est, haec autem vitia in omnibus stultis aeque magna sunt, necesse est paria esse peccata. Maxime autem in hoc quidem genere vis est perspicua naturae, cum et mendicitatem multi perpetiantur, ut vivant, et angantur adpropinquatione mortis confecti homines senectute et ea perferant, quae Philoctetam videmus in fabulis. Cum autem dispicere coepimus et sentire quid, simus et quid ab animantibus ceteris differamus, tum ea sequi incipimus, ad quae nati sumus. Quoniamque non dubium est quin in iis, quae media dicimus, sit aliud sumendum, aliud reiciendum, quicquid ita fit aut dicitur, omne officio continetur. Ita finis bonorum existit secundum naturam vivere sic affectum, ut optime is affici possit ad naturamque accommodatissime. Huic mori optimum esse propter desperationem sapientiae, illi propter spem vivere. Ne vitationem quidem doloris ipsam per se quisquam in rebus expetendis putavit, nisi etiam evitare posset. Qua exposita scire cupio quae causa sit, cur Zeno ab hac antiqua constitutione desciverit, quidnam horum ab eo non sit probatum; Est autem etiam actio quaedam corporis, quae motus et status naturae congruentis tenet; </p>

<p>Quid, si non modo utilitatem tibi nullam afferet, sed iacturae rei familiaris erunt faciendae, labores suscipiendi, adeundum vitae periculum? Video equidem, inquam, sed tamen iam infici debet iis artibus, quas si, dum est tener, conbiberit, ad maiora veniet paratior. Quibus ex omnibus iudicari potest non modo non impediri rationem amicitiae, si summum bonum in voluptate ponatur, sed sine hoc institutionem omnino amicitiae non posse reperiri. Studet enim meus is audire Cicero quaenam sit istius veteris, quam commemoras, Academiae de finibus bonorum Peripateticorumque sententia. Hoc autem loco tantum explicemus haec honesta, quae dico, praeterquam quod nosmet ipsos diligamus, praeterea suapte natura per se esse expetenda. Sed cum, quod honestum sit, id solum bonum esse dicamus, consentaneum tamen est fungi officio, cum id officium nec in bonis ponamus nec in malis. Ego autem: Ne tu, inquam, Cato, ista exposuisti, ut tam multa memoriter, ut tam obscura, dilucide, itaque aut omittamus contra omnino velle aliquid aut spatium sumamus ad cogitandum; His similes sunt omnes, qui virtuti student levantur vitiis, levantur erroribus, nisi forte censes Ti. Quid tanto concursu honestissimorum studiorum, tanto virtutum comitatu, si ea nullam ad aliam rem nisi ad voluptatem conquiruntur? Atque his tribus generibus honestorum notatis quartum sequitur et in eadem pulchritudine et aptum ex illis tribus, in quo inest ordo et moderatio. Teneamus enim illud necesse est, cum consequens aliquod falsum sit, illud, cuius id consequens sit, non posse esse verum. Leonidas autem, rex Lacedaemoniorum, se in Thermopylis trecentosque eos, quos eduxerat Sparta, cum esset proposita aut fuga turpis aut gloriosa mors, opposuit hostibus. </p>

<p>Equidem etiam curiam nostram-Hostiliam dico, non hanc novam, quae minor mihi esse videtur, posteaquam est maior-solebam intuens Scipionem, Catonem, Laelium, nostrum vero in primis avum cogitare; Scripta sane et multa et polita, sed nescio quo pacto auctoritatem oratio non habet. Vides igitur te aut ea sumere, quae non concedantur, aut ea, quae etiam concessa te nihil iuvent. Nihil enim desiderabile concupiscunt, plusque in ipsa iniuria detrimenti est quam in iis rebus emolumenti, quae pariuntur iniuria. Omne enim animal, simul et ortum est, se ipsum et omnes partes suas diligit duasque, quae maximae sunt, in primis amplectitur, animum et corpus, deinde utriusque partes. Fortitudinis quaedam praecepta sunt ac paene leges, quae effeminari virum vetant in dolore. Negat enim definiri rem placere, sine quo fieri interdum non potest, ut inter eos, qui ambigunt, conveniat quid sit id, de quo agatur, velut in hoc ipso, de quo nunc disputamus. </p>
PHP;


} 